version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: videojuegos-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/database.sqlite:/usr/src/app/backend/database.sqlite
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=supersecret_dev_key_change_me
